### ISSUE TITLE
Deprecated APIs are lacking availability information

### ISSUE THREAD

**Issue by karwa** [apple/swift-system#114]
I have a function which makes use of `FilePath(cString:)`, so it can be used as far back as macOS 11/iOS 14.

Now, I'm getting a warning that that initializer has been deprecated (in favour of `platformString:`). That's fine, but I'd still like to make use of the old initializer on those older OSes. Unfortunately, even when I only use the deprecated initializer on a fallback path, I still get warnings:

![image](https://user-images.githubusercontent.com/5254025/200769604-9fa7aab4-e824-4482-a2a2-d5941aa3f9c0.png)

I believe the reason for this is that the `@available` annotations do not include version information. It is possible to write something like:

`@available(macOS, introduced: 11, deprecated: 12)`

**Comment by glessard** [comment]
Linked to rdar://111935931

**Comment by glessard** [comment]
@karwa This was fixed in macOS 14.4 and the corresponding releases of iOS and watchOS. The deprecated API now include introduction versions in the SDK version of swift-system.

**Comment by glessard** [comment]
Fixed in macOS 14.4 and iOS 17.4 (and other corresponding releases). The deprecated API now include introduction versions in the SDK version of swift-system.
