### ISSUE TITLE
Why `import SystemPackage` instead of `import System`?

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-system#13]
Why is the target named `SystemPackage` instead of `System`?

**Comment by jabwd** [comment]
Im guessing its an umbrella import around many System{Suffix} targets to be able to better separate certain platform specifics in different modules. As you can see there is also a "SystemInternals" target, which implies that System in itself is only a prefix to many more possible targets if required/desired.

**Comment by milseman** [comment]
It's a workaround for current compiler limitations. If you have a binary `System` module available, as we do on Darwin and might have on other platforms in the future, then a `System` module from a package would conflict with that.

In the future the compiler might support module namespaces, which would allow us to name the module `System` in a package namespace distinct from one in a SDK or toolchain workspace. Alternatively or additionally, we might ship a binary `System` module for all platforms, in which case the package build would exist strictly for backwards deployment or prototyping.

**Comment by milseman** [comment]
I'm going to mark this as answered (i.e. closed), but feel free to ask further questions about this topic here.

**Comment by milseman** [comment]
Added to the FAQ: https://github.com/apple/swift-system/issues/18
