### ISSUE TITLE
Ship a quick interim 1.3.0 update resolving platform support issues

### ISSUE THREAD

**Issue by lorentey** [apple/swift-system#163]
We need to urgently tag a release that resolves critical platform support issues:

- https://github.com/apple/swift-system/pull/133
- https://github.com/apple/swift-system/pull/151
- https://github.com/apple/swift-system/pull/152

(Plus any other high-impact/low-complexity issues that are pending.)

To reduce prerelease testing costs, I'm planning to ship these in a new minor release, so that we can retire support for ancient Swift toolchains. This means we'd blow the 1.3.0 version number on this interim release, and the pending new feature additions will ship in 1.4.0 instead. (Hopefully in the foreseeable future.)

**Comment by lorentey** [comment]
I'm renaming the existing 1.3.0 milestone to 1.4.0 and opening a new 1.3.0 that's dedicated to this (much small) interim release.

**Comment by lorentey** [comment]
1.3.0 → 1.4.0 progress:

- [x] Existing 1.3.0 milestone renamed to [1.4.0](https://github.com/apple/swift-system/milestone/1)
- [x] [New milestone](https://github.com/apple/swift-system/milestone/2) opened for the interim 1.3.0 release
- [x] Existing release/1.3.0 branch [renamed to 1.4.0](https://github.com/apple/swift-system/tree/release/1.4.0)
- [x] New [release/1.3.0](https://github.com/apple/swift-system/tree/release/1.3.0) branch opened, starting from the current 1.2.1 tag
- [x] PR filed to update version annotations on release/1.4.0 (https://github.com/apple/swift-system/pull/164)

Cherry picking can start.

**Comment by glessard** [comment]
One other possibility for cherry-picking: https://github.com/apple/swift-system/pull/148. It's quite simple, and only affects Android -- swift-system currently doesn't have a tag that builds on recent Android, and that would fix it.

**Comment by lorentey** [comment]
I think we have picked all the cherries we are planning to ship in 1.3.0; prerelease validation testing can begun.

**Comment by lorentey** [comment]
Post-merge health check:

macOS (6.0 and main snapshots), Linux (5.8, 5.9, 5.10, 6.0 snapshots, main snapshots): https://ci.swift.org/view/Swift%20Packages%20-%202/view/swift-system/view/release_1.3.0/

Windows (main snapshots):
https://ci-external.swift.org/view/xInfrastructure/job/nightly-main-windows/job/swift-system/

**Comment by glessard** [comment]
Draft release notes:

This release primarily addresses a number of platform support issues.

## What's New

- Support for visionOS
- Support for musl libc

## What's Changed

- swift-system now requires Swift 5.8
- The `Collection` conformance of the  `SystemString` has been improved. This makes it compatible with the Swift 6.0 standard library, in which `Array`'s `replaceSubrange()` has become stricter about the correctness of the `Collection` types it handles.
- The cmake configuration now understands more spellings for Arm64, improving compatibility with Windows compilers.
- Adapted two syscall wrappers to support unusual nullability annotations in Android's NDK 26. The package needs this to build against recent NDKs.

## New Contributors

- [@MaxDesiatov](https://github.com/MaxDesiatov) made their first contribution in https://github.com/apple/swift-system/pull/133, cherry-picked here.
- [@finagolfin](https://github.com/finagolfin) made their first contribution in https://github.com/apple/swift-system/pull/148, cherry-picked here.
- [@hjyamauchi](https://github.com/hjyamauchi) made their first contribution in https://github.com/apple/swift-system/pull/151, cherry-picked here.
- [@noahpistilli](https://github.com/noahpistilli) made their first contribution in https://github.com/apple/swift-system/pull/152, adapted here.

Full Changelog: https://github.com/apple/swift-system/compare/1.2.1...release/1.3.0

**Comment by lorentey** [comment]
The CMake configuration appears to not be functional on macOS at least. I'm investigating.

```
$  cmake -S . -B "/tmp/b" -G Ninja
[...]
$ ninja -C /tmp/b -v
.../swift-system/Sources/System/Internals/CInterop.swift:38:27: error: cannot find type 'mode_t' in scope
  public typealias Mode = mode_t
                          ^~~~~~
.../swift-system/Sources/System/FilePermissions.swift:21:15: error: type 'FilePermissions' does not conform to protocol 'Decodable'
public struct FilePermissions: OptionSet, Hashable, Codable {
              ^
Swift.Decodable:2:5: note: protocol requires initializer 'init(from:)' with type 'Decodable'
    init(from decoder: any Decoder) throws
    ^
...
.../swift-system/Sources/System/FilePermissions.swift:121:50: error: no exact matches in call to initializer 
  public static var setUserID: FilePermissions { FilePermissions(0o4000) }
                                                 ^
Swift.SetAlgebra:2:23: note: candidate requires that 'Int' conform to 'Sequence' (requirement specified as 'S' : 'Sequence')
    @inlinable public init<S>(_ sequence: __owned S) where S : Sequence, Self.Element == S.Element
                      ^
.../swift-system/Sources/System/FilePermissions.swift:121:50: note: candidate expects value of type 'FilePermissions' for parameter #1 (got 'Int')
  public static var setUserID: FilePermissions { FilePermissions(0o4000) }
                                                 ^
...
.../swift-system/Sources/System/Internals/CInterop.swift:29:8: error: Unsupported Platform
#error("Unsupported Platform")
       ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by lorentey** [comment]
Ah cool, CMake does not know about the `SYSTEM_PACKAGE_DARWIN` hack.

**Comment by lorentey** [comment]
Fixed in #177.

**Comment by lorentey** [comment]
I filed https://github.com/apple/swift/pull/73656 to validate our CMake config in toolchain builds.

If this looks good, I think we'll be ready for tagging.

**Comment by glessard** [comment]
The toolchain builds were successful!

**Comment by glessard** [comment]
1.3.0 is released: https://github.com/apple/swift-system/releases/tag/1.3.0
