### ISSUE TITLE
Could you please remove the v-prefix from the version 0.0.2 tag?

### ISSUE THREAD

**Issue by kishikawakatsumi** [apple/swift-system#49]
The tag for version 0.0.2 now has a prefix of `v`, unlike the previous tag, which is now `v0.0.2`.

This will affect automatic updates of Renovate (https://github.com/apps/renovate).
Renovate will automatically create a PR from the GitHub tag as follows

```diff
-.package(url: "https://github.com/apple/swift-system", from: "0.0.1"),
+.package(url: "https://github.com/apple/swift-system", from: "v0.0.2"),
```

This causes an error in the Swift Package Manager.

```
...
[5/5] RUN cd ./swiftfiddle.com/_Packages/ && swift build -c release:
#8 1.044 /swiftfiddle.com/_Packages: error: manifest parse error(s):
#8 1.044 Invalid semantic version string 'v0.0.2'
...
```

If it's not important to add the `v` prefix, could you please revert to the previous format (like `0.0.2`)?

**Comment by milseman** [comment]
Argh, Github even recommends the v prefix through the release UI. I changed it to just use the semver for the tag, hopefully that fixes any issues you have.

**Comment by kishikawakatsumi** [comment]
Thank you so much for fixing it so quickly ☺️
