### ISSUE TITLE
Better Way Of Defining Linux System Constants

### ISSUE THREAD

**Issue by ldo** [apple/swift-system#5]
So the Linux constants may vary from one architecture to another. Why not get the actual values from the Linux system itself? Incorporate a script like this into your build process for Linux, by including its output in the generated source file:

    #/usr/bin/python3
    #+
    # Better way of defining constants for this
    # <https://github.com/apple/swift-system/blob/main/Sources/System/LinuxPlatformConstants.swift>
    # source file.
    #-

    import sys
    import os
    import subprocess
    import tempfile
    import shutil

    consts_to_define = \
        (
            {
                "symbols" :
                    [
                        "EPERM", "ENOENT", "ESRCH", "EINTR", "EIO", "ENXIO",
                        "E2BIG", "ENOEXEC", "EBADF", "ECHILD", "EAGAIN", "ENOMEM",
                        "EACCES", "EFAULT", "ENOTBLK", "EBUSY", "EEXIST", "EXDEV",
                        "ENODEV", "ENOTDIR", "EISDIR", "EINVAL", "ENFILE", "EMFILE",
                        "ENOTTY", "ETXTBSY", "EFBIG", "ENOSPC", "ESPIPE", "EROFS",
                        "EMLINK", "EPIPE", "EDOM", "ERANGE", "EDEADLK", "ENAMETOOLONG",
                        "ENOLCK", "ENOSYS", "ENOTEMPTY", "ELOOP", "EWOULDBLOCK", "ENOMSG",
                        "EIDRM", "ECHRNG", "EL2NSYNC", "EL3HLT", "EL3RST", "ELNRNG",
                        "EUNATCH", "ENOCSI", "EL2HLT", "EBADE", "EBADR", "EXFULL",
                        "ENOANO", "EBADRQC", "EBADSLT", "EDEADLOCK", "EBFONT", "ENOSTR",
                        "ENODATA", "ETIME", "ENOSR", "ENONET", "ENOPKG", "EREMOTE",
                        "ENOLINK", "EADV", "ESRMNT", "ECOMM", "EPROTO", "EMULTIHOP",
                        "EDOTDOT", "EBADMSG", "EOVERFLOW", "ENOTUNIQ", "EBADFD", "EREMCHG",
                        "ELIBACC", "ELIBBAD", "ELIBSCN", "ELIBMAX", "ELIBEXEC", "EILSEQ",
                        "ERESTART", "ESTRPIPE", "EUSERS", "ENOTSOCK", "EDESTADDRREQ", "EMSGSIZE",
                        "EPROTOTYPE", "ENOPROTOOPT", "EPROTONOSUPPORT", "ESOCKTNOSUPPORT",
                        "EOPNOTSUPP", "ENOTSUP", "EPFNOSUPPORT", "EAFNOSUPPORT", "EADDRINUSE",
                        "EADDRNOTAVAIL", "ENETDOWN", "ENETUNREACH", "ENETRESET", "ECONNABORTED",
                        "ECONNRESET", "ENOBUFS", "EISCONN", "ENOTCONN", "ESHUTDOWN", "ETOOMANYREFS",
                        "ETIMEDOUT", "ECONNREFUSED", "EHOSTDOWN", "EHOSTUNREACH", "EALREADY",
                        "EINPROGRESS", "ESTALE", "EUCLEAN", "ENOTNAM", "ENAVAIL", "EISNAM",
                        "EREMOTEIO", "EDQUOT", "ENOMEDIUM", "EMEDIUMTYPE", "ECANCELED",
                        "ENOKEY", "EKEYEXPIRED", "EKEYREVOKED", "EKEYREJECTED", "EOWNERDEAD",
                        "ENOTRECOVERABLE", "ERFKILL", "EHWPOISON",
                    ],
                "defines" : [],
                "includes" : ["errno.h"],
                "mark" : "errno",
            },
            {
                "symbols" :
                    [
                        "O_ACCMODE", "O_RDONLY", "O_WRONLY", "O_RDWR",
                        "O_CREAT", "O_EXCL", "O_NOCTTY", "O_TRUNC",
                        "O_APPEND", "O_NONBLOCK", "O_DSYNC", "FASYNC",
                        "O_DIRECT", "O_LARGEFILE", "O_DIRECTORY",
                        "O_NOFOLLOW", "O_NOATIME", "O_CLOEXEC",
                        "SEEK_SET", "SEEK_CUR", "SEEK_END",
                    ],
                "defines" : ["_GNU_SOURCE", "_LARGEFILE64_SOURCE"],
                "includes" : ["sys/types.h", "sys/stat.h", "fcntl.h"],
                "mark" : "File Operations",
            },
        )

    sys.stdout.write("#if os(Linux)\n")
    for consts_entry in consts_to_define :
        tempdir = tempfile.mkdtemp(prefix = "swift-consts-")
        srcfilename = "defconsts.c"
        exefilename = "defconsts"
        srcfile = open(os.path.join(tempdir, srcfilename), "wt")
        for define in consts_entry["defines"] :
            srcfile.write("#define %s\n" % define)
        #end for
        for include in consts_entry["includes"] :
            srcfile.write("#include <%s>\n" % include)
        #end for
        srcfile.write \
          (
            "#include <stdio.h>\n"
            "\n"
            "int main(void)\n"
            "  {\n"
          )
        srcfile.write \
          (
                "    fputs(\"\\n// MARK: %s\\n\", stdout);\n"
            %
                consts_entry["mark"]
          )
        for symbol in consts_entry["symbols"] :
            srcfile.write("    fputs(\"\\n@_alwaysEmitIntoClient\\n\", stdout);\n")
            srcfile.write \
              (
                    "    fprintf(stdout, \"internal var _%(symbol)s: CInt { %%d }\\n\", %(symbol)s);\n"
                %
                    {"symbol" : symbol}
              )
        #end for
        srcfile.write \
          (
            "    return 0;\n"
            "  } /*main*/\n"
          )
        srcfile.close()
        subprocess.check_call \
          (
            args = ("gcc", "-o", exefilename, srcfilename),
            cwd = tempdir
          )
        sys.stdout.write \
          (
            subprocess.check_output
              (
                args = ("./" + exefilename,),
                cwd = tempdir,
                text = True
              )
          )
        shutil.rmtree(tempdir, ignore_errors = True)
    #end for
    sys.stdout.write("\n#endif\n")

I’m sure you can see how to extend it to add other groups of constants as needed.

**Comment by milseman** [comment]
Thanks for posting this. We're definitely in a tough due to language/compiler limitations around emitting these constants, hence why we have the hard-coded values. Ideally, we'd get language support to just forward the constants from the headers, but in the meantime we may have to resort to code-gen for this.

**Comment by milseman** [comment]
https://github.com/apple/swift-system/pull/22 is also aiming at addressing this. It would be ideal if that could be a self-hosted script whose artifacts we can check in, giving us bootstrapping and automatic regression checks.

**Comment by ldo** [comment]
Not a fan of putting automatically-generated stuff into version control. Especially not stuff that is crucially dependent on the current system setup.

**Comment by milseman** [comment]
Good news, this is no longer required: https://github.com/apple/swift-system/pull/29
