### ISSUE TITLE
Double-free with FilePath in Xcode 13 beta

### ISSUE THREAD

**Issue by varungandhi-apple** [apple/swift-system#53]
Originally reported as https://bugs.swift.org/browse/SR-14895 by @Frizlab.

> FilePath crashes (double-free) with the following code
>
> ```swift
> import Foundation
> import System
>
> if #available(macOS 12.0, *) {
> 	let relative = FilePath("Versions")
> 	_ = FilePath("/a/b/c").appending(relative.components)
> 	print(relative)
> }
> ```
> Demo repo: https://gitlab.com/frizlab-demo-projects/pathcrash
>
> It does not crash when using SystemPackage version 0.0.2 instead of System (either in release or debug compilation mode).
>
> Configuration: macOS 12.0 Beta (21A5268h) with Xcode 13.0 beta (13A5155e)

**Comment by Frizlab** [comment]
Note it only crashes when using the pre-built System framework in macOS 12 beta, not when using SystemPackage via SPM.

**Comment by milseman** [comment]
This is due to a bug in the compiler (it doesn't emit consuming annotations in swift interface files), which will hopefully be fixed soon.

**Comment by Frizlab** [comment]
Seems fixed in macOS `21A5304g`, Xcode 13 beta 5 (`13A5212g`).
The issue can probably closed (I don’t seem to have the permission to do that).
